# Generated by Django 4.1 on 2022-10-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='p_email',
            new_name='person_mail',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_name',
            new_name='person_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_phone',
            new_name='person_phone',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='dep_decription',
            new_name='dep_details',
        ),
    ]
