# Generated by Django 4.1 on 2022-10-19 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_rename_p_email_booking_person_mail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='person_mail',
            new_name='patient_mail',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='person_name',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='person_phone',
            new_name='patient_phone',
        ),
    ]
